---
title: Bristol Comedy Garden
timezone: UTC
collections:
  line-up:
    title: Line-up
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: false
defaults:
- scope:
    path: ''
    type: pages
  values:
    layout: page
url: http://bristolcomedygarden.co.uk
description: Bristol Comedy Garden returns this summer for another series of unmissable
  shows!
permalink: pretty
exclude:
- Gemfile
- Gemfile.lock
- bower.json
- package.json
- config.codekit3
- README*
- LICENSE*
- CHANGELOG*
- node_modules
- ".gitignore"
- bower_components
gems:
- jekyll-seo-tag
- jekyll-sitemap
- jekyll-feed
markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: false
highlighter: rouge
company: 57 Festivals Ltd
date: "14 â€” 18 June 2017"
address: Queen Square, Bristol BS1 4QS
email: info@bristolcomedygarden.co.uk
google_site_verification: 
analytics: UA-49569208-1
logo: "/assets/img/logo.svg"
per_page: 12
date_format: "%b %d, %Y"
future: true
social:
  facebook: https://www.facebook.com/bristolcomedygarden
  instagram: https://www.instagram.com/bristolcomedygarden
  twitter: https://twitter.com/comedygarden
compress_html:
  clippings: []
  comments:
  - "<!-- "
  - " -->"
  endings: []
  ignore:
    envs: []
  blanklines: true
  profile: false
  startings: []